// Bundles the project's two typefaces in `public/fonts/` for the on-screen
// preview only. The print asset is generated by `lib/text.ts`, which
// bakes the glyphs into inline SVG paths so the on-screen preview and the
// printer asset look identical regardless of which fonts the host has
// installed.
//
// Both fonts are SIL Open Font Licensed.
// (Defined as a side-effect so other modules can import the directory
// constant if needed in the future.)

export const FONTS_DIR_PUBLIC = "/fonts/";
