// Server-side rasteriser: SVG -> PNG at Prodigi print resolution, with bundled fonts.
//
// Uses the WebAssembly build of resvg, with the .wasm binary and the fonts embedded as base64
// (lib/assets.js, generated by scripts/build-assets.mjs). This makes the function bundle
// self-contained: no native binaries, no file tracing, identical output on every platform.
import * as resvg from '@resvg/resvg-wasm';
import { WASM_B64, FONTS_B64 } from './assets.js';

let fontBuffers;
function fonts() {
  if (!fontBuffers) fontBuffers = FONTS_B64.map((b) => Buffer.from(b, 'base64'));
  return fontBuffers;
}

let ready;
export function getEngine() {
  if (!ready) {
    ready = resvg.initWasm(Buffer.from(WASM_B64, 'base64'))
      .catch((e) => { if (!/already/i.test(String(e))) throw e; })
      .then(() => ({ kind: 'wasm' }));
  }
  return ready;
}

/** Rasterise an SVG string. `width` lets callers ask for a smaller image (e.g. a preview). */
export async function svgToPng(svg, width) {
  await getEngine();
  const r = new resvg.Resvg(svg, {
    fitTo: width ? { mode: 'width', value: width } : { mode: 'original' },
    font: { fontBuffers: fonts(), loadSystemFonts: false, defaultFontFamily: 'IBM Plex Mono' },
    background: 'rgba(0,0,0,0)',
    shapeRendering: 2,
    textRendering: 2,
    imageRendering: 0,
  });
  return Buffer.from(r.render().asPng());
}
