// Generates lib/resvg-wasm.ts with the resvg WASM binary embedded as base64.
// Embedding keeps the renderer platform-independent (no native modules), so the
// same bundle runs on macOS in development and linux-arm64 on Vercel.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = require.resolve('@resvg/resvg-wasm/index_bg.wasm');

const b64 = readFileSync(wasmPath).toString('base64');
const out = `// AUTO-GENERATED by scripts/embed-resvg.mjs. Do not edit by hand.\n// Base64-encoded @resvg/resvg-wasm binary (MPL-2.0).\nexport const resvgWasmBase64 = '${b64}';\n`;
writeFileSync(join(__dirname, '..', 'lib', 'resvg-wasm.ts'), out);
console.log('Wrote lib/resvg-wasm.ts', out.length, 'bytes');
