// Generates lib/fonts.ts with base64-embedded font files so the fonts are
// guaranteed to be present inside the serverless bundle (no file tracing).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(__dirname, '..', 'lib', 'fonts');

const fonts = {
  playfairRegular: 'PlayfairDisplay-Regular.ttf',
  playfairBold: 'PlayfairDisplay-Bold.ttf',
  montserratRegular: 'Montserrat-Regular.ttf',
  montserratMedium: 'Montserrat-Medium.ttf',
  montserratSemiBold: 'Montserrat-SemiBold.ttf',
  montserratBold: 'Montserrat-Bold.ttf',
};

let out = '// AUTO-GENERATED by scripts/embed-fonts.mjs. Do not edit by hand.\n';
out += '// Base64-encoded TTF fonts (SIL Open Font License) used to convert text to vector outlines.\n\n';
for (const [key, file] of Object.entries(fonts)) {
  const b64 = readFileSync(join(fontsDir, file)).toString('base64');
  out += `export const ${key} = '${b64}';\n`;
}

writeFileSync(join(__dirname, '..', 'lib', 'fonts.ts'), out);
console.log('Wrote lib/fonts.ts', out.length, 'bytes');
