#!/usr/bin/env node
// Builds the two embedded astronomy data files for the Nightshift renderer.
//
//   public/js/stars.js          bright-star catalogue (HYG v41, mag <= 5.25)
//   public/js/constellations.js IAU constellation stick figures (d3-celestial)
//
// Both sources publish J2000 equatorial coordinates in degrees, which is what
// the renderer projects; run `npm run build-data` to regenerate.
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HYG_URL =
  'https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/CURRENT/hygdata_v41.csv';
const LINES_URL =
  'https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/constellations.lines.json';

const MAG_LIMIT = 5.25;
const outDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'public', 'js');
await mkdir(outDir, { recursive: true });

// ---- stars -------------------------------------------------------------
const csv = await (await fetch(HYG_URL)).text();
const header = csv.slice(0, csv.indexOf('\n')).split(',').map((name) => name.replace(/"/g, ''));
const columns = {};
for (const [index, name] of header.entries()) columns[name] = index;
const stars = [];
for (const line of csv.split('\n').slice(1)) {
  if (!line) continue;
  const cells = line.split(',');
  const mag = Number.parseFloat(cells[columns.mag]);
  const ra = Number.parseFloat(cells[columns.ra]);   // degrees, J2000
  const dec = Number.parseFloat(cells[columns.dec]); // degrees, J2000
  if (!Number.isFinite(mag) || mag > MAG_LIMIT) continue;
  if (!Number.isFinite(ra) || !Number.isFinite(dec)) continue;
  stars.push([ra, dec, Math.round(mag * 100) / 100]);
}
stars.sort((a, b) => a[2] - b[2]); // brightest first
const starsModule = `// Generated by tools/build-data.mjs from the HYG database v41
// (https://github.com/astronexus/HYG-Database, CC BY-SA 4.0) — stars with
// magnitude <= ${MAG_LIMIT}, [ra, dec, mag] in J2000 degrees, brightest first.
export const STARS = ${JSON.stringify(stars)};
`;
await writeFile(path.join(outDir, 'stars.js'), starsModule);

// ---- constellation stick figures ----------------------------------------
const geo = await (await fetch(LINES_URL)).json();
const constellations = geo.features.map((feature) =>
  feature.geometry.coordinates.map((polyline) =>
    polyline.map(([ra, dec]) => [Math.round(ra * 100) / 100, Math.round(dec * 100) / 100]),
  ),
);
const linesModule = `// Generated by tools/build-data.mjs from d3-celestial's constellation
// figures (https://github.com/ofrohn/d3-celestial, BSD-2-Clause) — IAU stick
// figures as [[ra, dec] per vertex] polylines, J2000 degrees.
export const CONSTELLATION_LINES = ${JSON.stringify(constellations)};
`;
await writeFile(path.join(outDir, 'constellations.js'), linesModule);

console.log(`stars: ${stars.length} (mag <= ${MAG_LIMIT})`);
console.log(`constellations: ${constellations.length}`);
console.log(`wrote public/js/stars.js and public/js/constellations.js`);
