"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { suites } from "./data";

function Markdown({ source }: { source: string }) {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        a: ({ children, ...props }) => <a {...props} target="_blank" rel="noreferrer">{children}</a>,
      }}
    >
      {source}
    </ReactMarkdown>
  );
}

export default function Viewer() {
  const [suiteId, setSuiteId] = useState(suites[0].id);
  const [background, setBackground] = useState("#30363d");
  const [documents, setDocuments] = useState<Record<string, string>>({});

  const suite = useMemo(
    () => suites.find((candidate) => candidate.id === suiteId) ?? suites[0],
    [suiteId],
  );

  useEffect(() => {
    let current = true;
    const paths = [suite.summary, ...suite.runs.map((run) => run.finalOutput)];
    const missing = paths.filter((documentPath) => documents[documentPath] === undefined);

    if (missing.length > 0) {
      Promise.all(missing.map(async (documentPath) => {
        try {
          const response = await fetch(documentPath);
          if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
          return [documentPath, await response.text()] as const;
        } catch (error) {
          return [documentPath, `Could not load ${documentPath}: ${error}`] as const;
        }
      }))
        .then((entries) => {
          if (current) setDocuments((existing) => ({ ...existing, ...Object.fromEntries(entries) }));
        });
    }

    return () => {
      current = false;
    };
  }, [documents, suite]);

  return (
    <main>
      <header>
        <h1>Benchmark run viewer</h1>
        <p>Every recovered shirt-design canvas for one suite, shown without cropping.</p>
      </header>

      <section className="controls" aria-label="Viewer controls">
        <label>
          Suite
          <select value={suite.id} onChange={(event) => setSuiteId(event.target.value)}>
            {suites.map((candidate) => (
              <option key={candidate.id} value={candidate.id}>{candidate.label}</option>
            ))}
          </select>
        </label>
        <label className="color-control">
          Design background
          <span>
            <input
              type="color"
              value={background}
              onChange={(event) => setBackground(event.target.value)}
              aria-label="Design background color"
            />
            <input type="text" value={background} readOnly aria-label="Design background hex color" />
          </span>
        </label>
        <a href="#suite-summary">Jump to summary</a>
      </section>

      <section className="suite-heading">
        <div>
          <h2>{suite.label}</h2>
          <p>{suite.runs.length > 0 ? `${suite.runs.length} recovered designs` : "Summary only"}</p>
        </div>
        <a href={suite.summary} download>Download summary.md</a>
      </section>

      {suite.runs.length > 0 ? (
        <section className="design-grid" aria-label={`${suite.label} designs`}>
          {suite.runs.map((run) => (
            <article className="design-card" key={run.id}>
              <div className="card-heading">
                <div>
                  <h3>{run.model}</h3>
                  <p>{run.status}</p>
                </div>
                <code>{run.commit}</code>
              </div>

              <div
                className="art-canvas"
                style={{ aspectRatio: `${run.width} / ${run.height}`, backgroundColor: background }}
              >
                <Image
                  src={run.design}
                  alt={`Full print canvas generated by ${run.model}`}
                  fill
                  sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw"
                  unoptimized
                />
              </div>

              <p className="image-meta">{run.width} × {run.height}px · {run.alpha}</p>
              <p className="evidence">{run.evidence}</p>
              <div className="card-links">
                <a href={run.design} download>Download design</a>
                <a href={run.deployment} target="_blank" rel="noreferrer">Storefront ↗</a>
              </div>

              <details>
                <summary>Final output</summary>
                <div className="markdown final-output">
                  <Markdown source={documents[run.finalOutput] ?? "Loading…"} />
                </div>
              </details>
            </article>
          ))}
        </section>
      ) : (
        <section className="summary-only">
          <p>This earlier suite has a normalized report, but its per-run artwork has not been recovered for the viewer.</p>
        </section>
      )}

      <section className="summary-section" id="suite-summary">
        <div className="section-heading">
          <div>
            <h2>Suite summary</h2>
            <p>Rendered from the generated Markdown report.</p>
          </div>
          <a href={suite.summary} download>Download .md</a>
        </div>
        <div className="markdown">
          <Markdown source={documents[suite.summary] ?? "Loading…"} />
        </div>
      </section>
    </main>
  );
}
