// Builds public/shared/skydata.js from the d3-celestial catalogs (BSD-3, github.com/ofrohn/d3-celestial).
// Usage: node scripts/build-data.js /path/to/d3-celestial/data
import fs from 'node:fs';
import path from 'node:path';

const src = process.argv[2] || '/tmp/ovdata';
const read = (f) => JSON.parse(fs.readFileSync(path.join(src, f), 'utf8'));
const r2 = (n) => Math.round(n * 100) / 100;
const MAG_LIMIT = 5.3;

const stars = read('stars.6.json').features
  .filter((f) => f.properties.mag <= MAG_LIMIT)
  .sort((a, b) => a.properties.mag - b.properties.mag)
  .flatMap((f) => [r2(f.geometry.coordinates[0]), r2(f.geometry.coordinates[1]), r2(f.properties.mag)]);

const lines = read('constellations.lines.json').features.flatMap((f) =>
  f.geometry.coordinates.map((line) => line.flatMap(([ra, dec]) => [r2(ra), r2(dec)]))
);

const names = read('constellations.json').features
  .filter((f) => Number(f.properties.rank) <= 2)
  .map((f) => [f.properties.name, r2(f.geometry.coordinates[0]), r2(f.geometry.coordinates[1])]);

const out = `// Generated by scripts/build-data.js — star data from d3-celestial (BSD-3-Clause), Hipparcos/Yale BSC.
// STARS: flat [raDeg, decDeg, mag, ...] (J2000), brightest first. LINES: constellation stick figures.
export const STARS = ${JSON.stringify(stars)};
export const LINES = ${JSON.stringify(lines)};
export const CONSTELLATIONS = ${JSON.stringify(names)};
`;
fs.writeFileSync(new URL('../public/shared/skydata.js', import.meta.url), out);
console.log(`stars=${stars.length / 3} lines=${lines.length} names=${names.length} bytes=${out.length}`);
