// Embeds the resvg WASM binary and the print fonts into lib/assets.js as base64 so the
// serverless bundle never depends on file tracing. Re-run after changing fonts.
import { readFileSync, writeFileSync } from 'node:fs';
const fonts = ['DMSerifDisplay-Regular.ttf', 'DMSerifDisplay-Italic.ttf', 'IBMPlexMono-Regular.ttf', 'IBMPlexMono-Medium.ttf', 'IBMPlexMono-SemiBold.ttf'];
const wasm = readFileSync('node_modules/@resvg/resvg-wasm/index_bg.wasm').toString('base64');
const fontB64 = fonts.map((f) => readFileSync(`lib/fonts/${f}`).toString('base64'));
const src = `// GENERATED by scripts/build-assets.mjs — do not edit.\n// resvg ${JSON.parse(readFileSync('node_modules/@resvg/resvg-wasm/package.json')).version} WASM + fonts (SIL OFL): ${fonts.join(', ')}\nexport const WASM_B64 = ${JSON.stringify(wasm)};\nexport const FONTS_B64 = ${JSON.stringify(fontB64)};\n`;
writeFileSync('lib/assets.js', src);
console.log('lib/assets.js', (src.length / 1024 / 1024).toFixed(1), 'MB');
